//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceAccounting.BusinessLogic.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperationsValidators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationsValidators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinanceAccounting.BusinessLogic.Resourses.OperationsValidators", typeof(OperationsValidators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not possible to specify a date from the future.
        /// </summary>
        public static string DateInFuture {
            get {
                return ResourceManager.GetString("DateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final date must be later than start date.
        /// </summary>
        public static string DatesConflict {
            get {
                return ResourceManager.GetString("DatesConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request contains duplicate operation ids.
        /// </summary>
        public static string DuplicateIds {
            get {
                return ResourceManager.GetString("DuplicateIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have a category with the specified id.
        /// </summary>
        public static string NoSuchCategory {
            get {
                return ResourceManager.GetString("NoSuchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have a operation with the specified id.
        /// </summary>
        public static string NoSuchOperation {
            get {
                return ResourceManager.GetString("NoSuchOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the specified id doesn&apos;t exist.
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
    }
}
